In [9]:
#%pip install kedro-datasets==[pandas] 
# ## pas besoin de cette ligne, les datasets sont déjà installés dans l'environnement virtuel du projet
## avec kedro-datasets==9.2.0

In [10]:
## pres requis 
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

# Load data via catalog : 
\spaceflights\conf\base\catalog.yml

### Contenue du catalog.yml
companies:
  type: pandas.CSVDataset
  filepath: data/01_raw/companies.csv

reviews:
  type: pandas.CSVDataset
  filepath: data/01_raw/reviews.csv

shuttles:
  type: pandas.ExcelDataset
  filepath: data/01_raw/shuttles.xlsx
  load_args:
    engine: openpyxl # Use modern Excel engine (the default since Kedro 0.18.0)

In [18]:
## load data
catalog.load("companies")

[03/19/26 01:38:29] INFO     Loading data from companies (CSVDataset)...                       data_catalog.py:1048

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t
...,...,...,...,...,...
10014,20213,NaN,Russian Federation,1.0,f
10015,2235,100%,Guinea,1.0,f
10016,2353,100%,Senegal,2.0,t
10017,49772,100%,Jersey,1.0,f
10018,16548,90%,NaN,2.0,f

In [19]:
catalog.load("reviews")

                    INFO     Loading data from reviews (CSVDataset)...                         data_catalog.py:1048

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29
...,...,...,...,...,...,...,...,...,...,...
15526,63513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
15527,44668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
15528,4368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
15529,21738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
15530,72645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [20]:
catalog.load("shuttles")

                    INFO     Loading data from shuttles (ExcelDataset)...                      data_catalog.py:1048

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15526,63513,Micronesia,Type V5,Plasma,ThetaBase Services,1.0,2,flexible,1.0,t,f,"$2,040.0",5816
15527,44668,Rwanda,Type F5,Quantum,ThetaBase Services,1.0,1,strict,1.0,t,f,"$1,260.0",19010
15528,4368,Barbados,Type V5,Quantum,ThetaBase Services,2.0,4,flexible,2.0,t,f,"$4,107.0",6654
15529,21738,Uzbekistan,Type V5,Plasma,ThetaBase Services,1.0,2,flexible,1.0,t,f,"$2,170.0",27363
15530,72645,Malta,Type F5,Quantum,ThetaBase Services,0.0,2,moderate,2.0,t,f,"$1,455.0",12542

# Explore the space flights data

## Companies Data

In [69]:
companies = catalog.load("companies")
print("companies.shape: \n" , companies.shape, "\n")
print("companies.dtypes: \n", companies.dtypes, "\n")
print("type(companies): \n", type(companies), "\n")
print("companies.head(): \n", companies.head().to_string(), "\n")

[03/19/26 02:15:14] INFO     Loading data from companies (CSVDataset)...                       data_catalog.py:1048

companies.shape:
 (10019, 5)

companies.dtypes:
 id                     int64
company_rating        object
company_location      object
total_fleet_count    float64
iata_approved         object
dtype: object

type(companies):
 <class 'pandas.core.frame.DataFrame'>

companies.head():
       id company_rating        company_location  total_fleet_count iata_approved
0   3888           100%             Isle of Man                1.0             f
1  46728           100%                     NaN                1.0             f
2  34618            38%             Isle of Man                1.0             f
3  28619           100%  Bosnia and Herzegovina                1.0             f
4   8240            NaN                   Chile                1.0             t

In [70]:
print("Treat the 'iata_approved' column")

print("unique values de la colonne iata_approved: \n", companies["iata_approved"].value_counts(), "\n")

print("Transform the 'iata_approved' column to boolean values: \n")
companies["iata_approved"] = companies["iata_approved"]== "t"

print("unique values de la colonne iata_approved après transformation: \n", companies["iata_approved"].value_counts(), "\n")

print("companies.dtypes: \n", companies.dtypes, "\n")
print("companies.head(): \n", companies.head().to_string(), "\n")

Treat the 'iata_approved' column
unique values de la colonne iata_approved:
 iata_approved
f    6001
t    4016
Name: count, dtype: int64

Transform the 'iata_approved' column to boolean values:

unique values de la colonne iata_approved après transformation:
 iata_approved
False    6003
True     4016
Name: count, dtype: int64

companies.dtypes:
 id                     int64
company_rating        object
company_location      object
total_fleet_count    float64
iata_approved           bool
dtype: object

companies.head():
       id company_rating        company_location  total_fleet_count  iata_approved
0   3888           100%             Isle of Man                1.0          False
1  46728           100%                     NaN                1.0          False
2  34618            38%             Isle of Man                1.0          False
3  28619           100%  Bosnia and Herzegovina                1.0          False
4   8240            NaN                   Chile                1.0           True

In [71]:
print("Treat the company_rating column")
print("Replace percentage signs in str values by empty string and convert the column to float: \n")
companies["company_rating"] = companies["company_rating"].str.replace("%", "").astype(float)
print("companies.dtypes: \n", companies.dtypes, "\n")
print("companies.head(): \n", companies.head().to_string(), "\n")

Treat the company_rating column
Replace percentage signs in str values by empty string and convert the column to float:

companies.dtypes:
 id                     int64
company_rating       float64
company_location      object
total_fleet_count    float64
iata_approved           bool
dtype: object

companies.head():
       id  company_rating        company_location  total_fleet_count  iata_approved
0   3888           100.0             Isle of Man                1.0          False
1  46728           100.0                     NaN                1.0          False
2  34618            38.0             Isle of Man                1.0          False
3  28619           100.0  Bosnia and Herzegovina                1.0          False
4   8240             NaN                   Chile                1.0           True

## reviews data

In [72]:
reviews = catalog.load("reviews")
print("reviews.shape: \n" , reviews.shape, "\n")
print("reviews.dtypes: \n", reviews.dtypes, "\n")
print("type(reviews): \n", type(reviews), "\n")
print("reviews.head(): \n", reviews.head().to_string(), "\n")
print("everything looks good in reviews dataset, no need to do any transformation for now \n")

[03/19/26 02:15:32] INFO     Loading data from reviews (CSVDataset)...                         data_catalog.py:1048

reviews.shape:
 (15531, 10)

reviews.dtypes:
 shuttle_id                   int64
review_scores_rating       float64
review_scores_comfort      float64
review_scores_amenities    float64
review_scores_trip         float64
review_scores_crew         float64
review_scores_location     float64
review_scores_price        float64
number_of_reviews            int64
reviews_per_month          float64
dtype: object

type(reviews):
 <class 'pandas.core.frame.DataFrame'>

reviews.head():
    shuttle_id  review_scores_rating  review_scores_comfort  review_scores_amenities  review_scores_trip  review_scores_crew  review_scores_location  review_scores_price  number_of_reviews  reviews_per_month
0       45163                  91.0                   10.0                      9.0                 9.0                 9.0                     9.0                  9.0                 26               0.77
1       49438                  96.0                   10.0                     10.0                10.0                10.0                    10.0                  9.0                 61               0.62
2       10750                  97.0                   10.0                     10.0                10.0                10.0                    10.0                 10.0                467               4.66
3        4146                  95.0                   10.0                     10.0                10.0                10.0                     9.0                  9.0                318               3.22
4        5067                  97.0                   10.0                      9.0                10.0                10.0                     9.0                 10.0                 22               0.29

everything looks good in reviews dataset, no need to do any transformation for now

## shuttles data

In [73]:
shuttles = catalog.load("shuttles")
print("shuttles.shape: \n" , shuttles.shape, "\n")
print("shuttles.dtypes: \n", shuttles.dtypes, "\n")
print("type(shuttles): \n", type(shuttles), "\n")
print("shuttles.head(): \n", shuttles.head().to_string(), "\n")

[03/19/26 02:15:37] INFO     Loading data from shuttles (ExcelDataset)...                      data_catalog.py:1048

shuttles.shape:
 (15531, 13)

shuttles.dtypes:
 id                           int64
shuttle_location            object
shuttle_type                object
engine_type                 object
engine_vendor               object
engines                    float64
passenger_capacity           int64
cancellation_policy         object
crew                       float64
d_check_complete            object
moon_clearance_complete     object
price                       object
company_id                   int64
dtype: object

type(shuttles):
 <class 'pandas.core.frame.DataFrame'>

shuttles.head():
       id       shuttle_location shuttle_type engine_type       engine_vendor  engines  passenger_capacity cancellation_policy  crew d_check_complete moon_clearance_complete     price  company_id
0  45163  Sao Tome and Principe      Type V5      Plasma  ThetaBase Services      2.0                   4            moderate   2.0                f                       f  $1,715.0       32413
1  49438      Wallis and Futuna      Type V2      Plasma  ThetaBase Services      3.0                   5            moderate   3.0                f                       f  $3,405.0       14122
2  10750                   Niue      Type F5     Quantum  ThetaBase Services      1.0                   2              strict   1.0                t                       f  $1,806.0       47761
3   4146                  Malta      Type V2     Quantum  ThetaBase Services      1.0                   2            moderate   1.0                f                       f  $1,676.0       26648
4   5067                  Malta      Type V2      Plasma  ThetaBase Services      5.0                  10              strict   5.0                f                       f  $4,718.0       26648

In [74]:
print("Treat the 'd_check_complete' and 'moon_clearance_complete' columns")

print("unique values of  d_check_complete: \n", shuttles["d_check_complete"].value_counts(), "\n")
print("unique values of  moon_clearance_complete: \n", shuttles["moon_clearance_complete"].value_counts(), "\n")

print("Transform the 'd_check_complete' and 'moon_clearance_complete' columns to boolean values: \n")
shuttles["d_check_complete"] = shuttles["d_check_complete"] == "t"
shuttles["moon_clearance_complete"] = shuttles["moon_clearance_complete"] == "t"

print("unique values de la colonne d_check_complete après transformation: \n", shuttles["d_check_complete"].value_counts(), "\n")
print("unique values de la colonne moon_clearance_complete après transformation: \n", shuttles["moon_clearance_complete"].value_counts(), "\n")

print("shuttles.dtypes: \n", shuttles.dtypes, "\n")
print("shuttles.head(): \n", shuttles.head().to_string(), "\n")

Treat the 'd_check_complete' and 'moon_clearance_complete' columns
unique values of  d_check_complete:
 d_check_complete
f    9389
t    6142
Name: count, dtype: int64

unique values of  moon_clearance_complete:
 moon_clearance_complete
f    15531
Name: count, dtype: int64

Transform the 'd_check_complete' and 'moon_clearance_complete' columns to boolean values:

unique values de la colonne d_check_complete après transformation:
 d_check_complete
False    9389
True     6142
Name: count, dtype: int64

unique values de la colonne moon_clearance_complete après transformation:
 moon_clearance_complete
False    15531
Name: count, dtype: int64

shuttles.dtypes:
 id                           int64
shuttle_location            object
shuttle_type                object
engine_type                 object
engine_vendor               object
engines                    float64
passenger_capacity           int64
cancellation_policy         object
crew                       float64
d_check_complete              bool
moon_clearance_complete       bool
price                       object
company_id                   int64
dtype: object

shuttles.head():
       id       shuttle_location shuttle_type engine_type       engine_vendor  engines  passenger_capacity cancellation_policy  crew  d_check_complete  moon_clearance_complete     price  company_id
0  45163  Sao Tome and Principe      Type V5      Plasma  ThetaBase Services      2.0                   4            moderate   2.0             False                    False  $1,715.0       32413
1  49438      Wallis and Futuna      Type V2      Plasma  ThetaBase Services      3.0                   5            moderate   3.0             False                    False  $3,405.0       14122
2  10750                   Niue      Type F5     Quantum  ThetaBase Services      1.0                   2              strict   1.0              True                    False  $1,806.0       47761
3   4146                  Malta      Type V2     Quantum  ThetaBase Services      1.0                   2            moderate   1.0             False                    False  $1,676.0       26648
4   5067                  Malta      Type V2      Plasma  ThetaBase Services      5.0                  10              strict   5.0             False                    False  $4,718.0       26648

In [82]:
shuttles["price"] = shuttles["price"].str.replace("$", "").str.replace(",", "").astype(float)
shuttles

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,False,1715.0,32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,False,3405.0,14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,False,1806.0,47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,False,1676.0,26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,False,4718.0,26648
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15526,63513,Micronesia,Type V5,Plasma,ThetaBase Services,1.0,2,flexible,1.0,True,False,2040.0,5816
15527,44668,Rwanda,Type F5,Quantum,ThetaBase Services,1.0,1,strict,1.0,True,False,1260.0,19010
15528,4368,Barbados,Type V5,Quantum,ThetaBase Services,2.0,4,flexible,2.0,True,False,4107.0,6654
15529,21738,Uzbekistan,Type V5,Plasma,ThetaBase Services,1.0,2,flexible,1.0,True,False,2170.0,27363
15530,72645,Malta,Type F5,Quantum,ThetaBase Services,0.0,2,moderate,2.0,True,False,1455.0,12542

0        1715.0
1        3405.0
2        1806.0
3        1676.0
4        4718.0
          ...
15526    2040.0
15527    1260.0
15528    4107.0
15529    2170.0
15530    1455.0
Name: price, Length: 15531, dtype: float64

# Refactoring prepare data in function

In [85]:
import pandas as pd

In [86]:
def _is_x_true(x:pd.Series) -> pd.Series:
    return x == "t"

def _parse_percentage(x:pd.Series) -> pd.Series:
    return x.str.replace("%", "").astype(float)

def _parse_money(x:pd.Series) -> pd.Series:
    return x.str.replace("$", "").str.replace(",", "").astype(float)

In [88]:
# test functions
companies = catalog.load("companies")
print("companies.head(): \n", companies.head().to_string(), "\n")
print("Treat the 'iata_approved' and 'company_rating' columns")
companies["iata_approved"] = _is_x_true(companies["iata_approved"])
companies["company_rating"] = _parse_percentage(companies["company_rating"])

print("companies.head(): \n", companies.head().to_string(), "\n")

shuttles = catalog.load("shuttles")
print("shuttles.head(): \n", shuttles.head().to_string(), "\n")
print("Treat the 'd_check_complete', 'moon_clearance_complete' and 'price' columns")
shuttles["d_check_complete"] = _is_x_true(shuttles["d_check_complete"])
shuttles["moon_clearance_complete"] = _is_x_true(shuttles["moon_clearance_complete"])
shuttles["price"] = _parse_money(shuttles["price"])
print("shuttles.head(): \n", shuttles.head().to_string(), "\n")

[03/19/26 02:33:52] INFO     Loading data from companies (CSVDataset)...                       data_catalog.py:1048

companies.head():
       id company_rating        company_location  total_fleet_count iata_approved
0   3888           100%             Isle of Man                1.0             f
1  46728           100%                     NaN                1.0             f
2  34618            38%             Isle of Man                1.0             f
3  28619           100%  Bosnia and Herzegovina                1.0             f
4   8240            NaN                   Chile                1.0             t

Treat the 'iata_approved' and 'company_rating' columns
companies.head():
       id  company_rating        company_location  total_fleet_count  iata_approved
0   3888           100.0             Isle of Man                1.0          False
1  46728           100.0                     NaN                1.0          False
2  34618            38.0             Isle of Man                1.0          False
3  28619           100.0  Bosnia and Herzegovina                1.0          False
4   8240             NaN                   Chile                1.0           True

                    INFO     Loading data from shuttles (ExcelDataset)...                      data_catalog.py:1048

shuttles.head():
       id       shuttle_location shuttle_type engine_type       engine_vendor  engines  passenger_capacity cancellation_policy  crew d_check_complete moon_clearance_complete     price  company_id
0  45163  Sao Tome and Principe      Type V5      Plasma  ThetaBase Services      2.0                   4            moderate   2.0                f                       f  $1,715.0       32413
1  49438      Wallis and Futuna      Type V2      Plasma  ThetaBase Services      3.0                   5            moderate   3.0                f                       f  $3,405.0       14122
2  10750                   Niue      Type F5     Quantum  ThetaBase Services      1.0                   2              strict   1.0                t                       f  $1,806.0       47761
3   4146                  Malta      Type V2     Quantum  ThetaBase Services      1.0                   2            moderate   1.0                f                       f  $1,676.0       26648
4   5067                  Malta      Type V2      Plasma  ThetaBase Services      5.0                  10              strict   5.0                f                       f  $4,718.0       26648

Treat the 'd_check_complete', 'moon_clearance_complete' and 'price' columns
shuttles.head():
       id       shuttle_location shuttle_type engine_type       engine_vendor  engines  passenger_capacity cancellation_policy  crew  d_check_complete  moon_clearance_complete   price  company_id
0  45163  Sao Tome and Principe      Type V5      Plasma  ThetaBase Services      2.0                   4            moderate   2.0             False                    False  1715.0       32413
1  49438      Wallis and Futuna      Type V2      Plasma  ThetaBase Services      3.0                   5            moderate   3.0             False                    False  3405.0       14122
2  10750                   Niue      Type F5     Quantum  ThetaBase Services      1.0                   2              strict   1.0              True                    False  1806.0       47761
3   4146                  Malta      Type V2     Quantum  ThetaBase Services      1.0                   2            moderate   1.0             False                    False  1676.0       26648
4   5067                  Malta      Type V2      Plasma  ThetaBase Services      5.0                  10              strict   5.0             False                    False  4718.0       26648